config/routes.rb
Rails.application.routes.draw do
  devise_for :shafus
  root to: 'results#index'
  get 'results/index', to: "results#index"
  resources :receipts, only: [:index, :new, :create, :show]
end

app/models/adult.rb
class Adult < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '1' },
    { id: 3, name: '2' },
  ]

  include ActiveHash::Associations
  has_many :receipts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/child.rb
class Child < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '1' },
    { id: 3, name: '2' },
    { id: 4, name: '3' },
  ]

  include ActiveHash::Associations
  has_many :receipts
end

app/models/course.rb
class Course < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '1区' },
    { id: 3, name: '特区' },
    { id: 4, name: '貸切' }
  ]

  include ActiveHash::Associations
  has_many :receipts
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :shafu
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :course
  belongs_to :adult
  belongs_to :child

  integer = /\A[1-9][0-9]+\z/
  validates :fee, format: {with: integer, message: 'permit only half-width numbers'}
  with_options numericality: {other_than: 1} do
    validates :course_id
  end
  with_options presence: true do
    validates :customer_name
    validates :fee
    validates :departure_from
    validates :arrive_at
    validates :departure_time
    validates :arrival_time
  end
  with_options inclusion: [true, false] do
    validates :cashless
    validates :group
  end
end

app/models/shafu.rb
class Shafu < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :receipts

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze
  zenkaku = /\A(?:\p{Hiragana}|\p{Katakana}|[ー－]|[一-龠々])+\z/
  zenkaku_katakana = /\A[ァ-ヶー－]+\z/
  validates :birthday, presence: true
  validates :password, format: { with: PASSWORD_REGEX, message: 'Include both letters and numbers' }
  with_options presence: true, format: { with: zenkaku, message: 'Full-width characters' } do
    validates :lname
    validates :fname
  end
  with_options presence: true, format: { with: zenkaku_katakana, message: 'Full-width katakana characters' } do
    validates :lname_katakana
    validates :fname_katakana
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:lname, :fname, :lname_katakana, :fname_katakana, :birthday])
  end
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :authenticate_shafu!, except: :show

  def index
    @receipts = Receipt.order('created_at DESC')
  end

  def new
    @receipt = Receipt.new
  end

  def create
    @receipt = Receipt.new(receipt_params)
    if @receipt.save
      qrcode_maker
    else
      render :new
    end
  end

  def show
    @receipt = Receipt.find(params[:id])
    pdf_maker
  end

  private
  def receipt_params
    params.require(:receipt).permit(:customer_name, :fee, :cashless, :course_id, :adult_id, :child_id, :group, :departure_from, :arrive_at, :departure_time, :arrival_time, :course_time, :overtime).merge(shafu_id: current_shafu.id, date:Date.today)
  end

  def pdf_maker
    respond_to do |format|
      format.html { redirect_to action: :show, format: :pdf, debug: true }
      format.pdf do
        render pdf: "receipt",
        layout: 'pdf.html.erb',
        template: "receipts/show.html.erb",
        encoding: 'UTF-8',
        show_as_html: params.key?('debug')
      end
    end
  end

  def qrcode_maker
    @receipt = Receipt.last
    @qr = RQRCode::QRCode.new("#{request.url}/#{@receipt.id}.pdf").as_svg.html_safe
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  def index
    receipts = Receipt.group("DAY(created_at)")
    @sums = receipts.sum(:fee)
    cussions = Receipt.select(:date).distinct
    dates = []
    cussions.each do |cussion|
      dates << cussion[:date]
    end
    @how_many_cars = []
    dates.each do |date|
      @how_many_cars << Receipt.where(date: date).select(:shafu_id).distinct.count
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rickshaw</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
  <%= wicked_pdf_javascript_include_tag 'application' %>
  <%= wicked_pdf_stylesheet_link_tag 'application' %>
</head>
<body>
  <%= yield %>
</div>
</body>
</html>

app/views/receipts/create.html.erb
<div class="qrpage">
  <h1 class="qrpage-title">こちら領収書のpdfです</h1>
  <span class="qr"><%= @qr %></span></br>
  <%= link_to "pdfビュー", "receipts/#{@receipt.id}.pdf" %></br>
  <%= link_to '戻る', receipts_path %>
</div>

app/views/receipts/index.html.erb
<div class="receipt-index-wrap">
  <div class="receipt-index-top">
    <%= "#{current_shafu.lname+current_shafu.fname}のページ" %>
  </div>
  <div class="receipt-index-btn-wrap">
    <div class="receipt-index-btn">
      <%= link_to '領収書作成', new_receipt_path %>
    </div>
    <div class="receipt-index-btn">
      <%= link_to '今日の成績', "#" %>
    </div>
  </div>
  <div class="receipts-wrap">
    <div class="receipts">
      <p class="receipts-title"><%= "#{Date.today.month}月#{Date.today.day}日のご案内一覧" %></p>
      <% @receipts.each do |receipt| %>
      <%# 当日の領収書だけを表示 %>
      <% if Date.today.year == receipt.created_at.year && Date.today.month == receipt.created_at.month && Date.today.day ==receipt.created_at.day %>
      <%# 俥夫本人の領収書だけを表示 %>
      <% if receipt.shafu_id == current_shafu.id %>
      <% i = 1 %>
      <div class="receipt">
        <%= link_to "#{i}. #{receipt.customer_name}", "receipts/#{receipt.id}.pdf" %>
      </div>
      <% i += 1 %>
      <% end %>
      <% end %>
      <% end %>
    </div>
  </div>
  <div class="receipt-index-btn-wrap">
    <div class="receipt-index-small-btn">
      <%= link_to '月間成績', "#" %>
    </div>
  </div>
</div>

app/views/receipts/new.html.erb
<div class="container">
  <p class="receipt-title">領収書</p>
  <%= form_with model:@receipt, url: receipts_path, local: true, class: "form-wrapper" do |f| %>

  <div class="form-contents">
    <%= render 'shared/error_messages', model: f.object %>
    
    <div class="form-content">
      <%= f.label :customer_name, "お宛名", class: "section-title" %></br>
      <%= f.text_field :customer_name, placeholder:"山田太郎様", class: "text-field" %>
    </div>
    
    <div class="form-content">
      <%= f.label :fee, "料金", class: "section-title" %></br>
      <%= f.text_field :fee, placeholder:"4000", class: "text-field" %></br>
      <%= f.label :cashless, "キャッシュレス" %>
      <%= f.check_box :cashless %>
    </div>
    
    <div class="form-content">
      <%= f.label :date, "乗車日", class: "section-title" %></br>
      <%= f.date_select Date.today, use_month_numbers: true %>
    </div>
    
    <div class="form-content">
      <p class="section-title">乗車人数</p>
      <%= f.label :adult_id, "大人" %>
      <%= f.collection_select(:adult_id, Adult.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %></br>
      <%= f.label :child_id, "小人" %>
      <%= f.collection_select(:child_id, Child.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %></br>
      <%= f.label :group, "団体" %>
      <%= f.check_box :group %>
    </div>
  
    <div class="form-content">
      <p class="section-title">コース</p>
      <%= f.collection_select(:course_id, Course.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %></br>
      <%= f.text_field :departure_from, placeholder:"出発地", class: "text-field" %></br>
      <%= f.text_field :arrive_at, placeholder:"到着地", class: "text-field" %></br>
      <%= f.label :departure_time, "出発" %>
      <%= f.time_select :departure_time %></br>
      <%= f.label :arrival_time, "到着" %>
      <%= f.time_select :arrival_time %></br>
      <%= f.text_field :course_time, placeholder:"ご案内時間", class: "text-field" %>
    </div>
    
    <div class="form-content">
      <p class="section-title">遅延理由</p>
      <%= f.label(:overtime, "T", value: "T") %>
      <%= f.radio_button :overtime, "T" %>
      <%= f.label(:overtime, "J", value: "J") %>
      <%= f.radio_button :overtime, "J" %>
      <%= f.label(:overtime, "A", value: "A") %>
      <%= f.radio_button :overtime, "A" %>
      <%= f.label(:overtime, "I", value: "I") %>
      <%= f.radio_button :overtime, "I" %>
    </div>
    
  </div>
  <div class="form-content">
      <%= f.submit "確定する" %>
  </div>
  <% end %>
</div>

app/views/receipts/show.html.erb
<div class="receipt-pdf">
    <div class="receipt-top">
      <p><%= "発行日#{@receipt.created_at.year}年#{@receipt.created_at.month}月#{@receipt.created_at.day}日" %></p>
      <p><%= "No.#{@receipt.id}" %></p>
    </div>
  <h2 class="receipt-title">領収書</h2>
  <div class="receipt-name">
      <p><%= @receipt.customer_name %></p>
  </div>
  <div class="fee-box">
  <p>金額</p>
    <p><%= "#{@receipt.fee.to_s.insert(-4,",")}円" %></p>
  </div>
  <div class="receipt-letter">
    <p>但し</p>
    <p>上記の金額正に受領いたしました</p>
  </div>
  <div class="company-info">
    <p>人力車株式会社</p>
    <p>〒１２３ー４５６７</p>
    <p>京都府〇〇市△区□町</p>
    <p>電話01-2345-6789</p>
    <p>FAX01-2345-6789</p>
  </div>
</div>

app/views/results/index.html.erb
<%= render "shared/header" %>
<div class="result-wrapper">
<p><%= "#{Date.today.month}月の業績" %></p>
<table class="table">
  <tr>
    <th class="table-header">日</th>
    <th class="table-header">総売上</th>
    <th class="table-header">稼働台数</th>
    <th class="table-header">台あたり</th>
  </tr>
  <% @sums.each_with_index do |sum, i| %>
  <tr>
    <td class="table-item"><%= sum[0] %></td>
    <td class="table-item"><%= sum[1] %></td>
    <td class="table-item"><%= @how_many_cars[i] %></td>
    <td class="table-item"><%= sum[1]/@how_many_cars[i] %></td>
  </tr>
  <% end %>
</table>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<%# CSS ・・・assets/stylesheets/shared/header.css まだ書いてない %>
<header>
  <div class="top-page-header">
    <div class="header-left">
        <%= link_to image_tag("rickshaw-logo.png", size: '100x100'), "/" %>
        <span>Rickshaw</span>
    </div>
    <div class="nav">
      <ul>
      <% if shafu_signed_in? %>
        <li><%= link_to 'ログアウト', destroy_shafu_session_path, method: :delete %></li>
        <li><%= link_to '領収書', receipts_path %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_shafu_session_path %></li>
        <li><%= link_to '新規登録', new_shafu_registration_path %></li>
      <% end %>
      </ul>
    </div>
  </div>
</header>